### ISSUE TITLE
TypeError: Cannot read property '0' of null / Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by m1chu** [szTheory/exifcleaner#59] opened 2020-06-05 16:22 UTC
I tried to add JPG files (smaller than 1.1MB) by `Open` or drag and drop function. And during load always got:

```
internal/process/task_queues.js:85 TypeError: Cannot read property '0' of null
    at webpack:/src/renderer/add_files.js:128
    at process.exifData (internal/process/task_queues.js:85)
    at webpack:/src/renderer/add_files.js:22
processTicksAndRejections @ internal/process/task_queues.js:85
internal/process/task_queues.js:85 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at updateRowWithExif (webpack:/src/renderer/table.js:9)
    at webpack:/src/renderer/add_files.js:27
    at processTicksAndRejections (internal/process/task_queues.js:85)
processTicksAndRejections @ internal/process/task_queues.js:85
```

![exif_cleaner](https://user-images.githubusercontent.com/1886660/83899807-577d9f80-a759-11ea-9402-d45831d98539.png)

**Comment by szTheory** [comment] 2020-06-05 17:21
Thanks for the report. Is it possible to provide a sample image that gives the error and you are OK with sharing? You can do so by dragging it into your Github message. Also it looks like you're on Windows, which version? Finally, can you provide the version number of ExifCleaner you're on?

**Comment by m1chu** [comment] 2020-06-05 21:46
Windows 10 Pro N (10.0.18363) and ExifCleaner 3.2.0. I will try to check again tomorrow and provide a sample photo to you.

**Comment by m1chu** [comment] 2020-06-06 21:43
Sample of an image:

![test](https://user-images.githubusercontent.com/1886660/83955052-43b46500-a84f-11ea-8c52-fb98adad5c74.jpg)

**Comment by szTheory** [comment] 2020-06-06 22:13
Thanks! Interesting, I wasn't able to reproduce with that image on a Windows 8 box using ExifCleaner 3.2.0. Just to confirm can you reproduce on your box with the same image you uploaded? (after re-saving it locally and dragging it into ExifCleaner). I'll have to set up a Windows 10 box and try this on it. And if I can't reproduce I'll have to poke around in the code to see if there is anything obvious that might be causing it.

**Comment by m1chu** [comment] 2020-06-07 10:13
I did some analysis and it looks like I've found what the problem may be.

### Comparing original image with downloaded from GitHub
I re-saved my photo from GitHub and tried to reuse ExifCleaner. Everything ended well. ExifCleaner didn't find any entries to delete (0), but also didn't complete with error.

Firstly I thought that the problem lies in the custom metadata format. It is strange, however when I compared both files, they look exactly the same:
|Category \ File|Original file|Downloaded from GitHub|
|-|-|-|
|File name|test.jpg|83955052-43b46500-a84f-11ea-8c52-fb98adad5c74.jpg|
|Size (bytes)|256 708|256 708|
|Size on disk (allocated)|258 048|258 048|
|SHA-1 hash of a file|`5919f8678e3d952749187559b649ab52c3e65ae1`|`5919f8678e3d952749187559b649ab52c3e65ae1`|
|ExifCleaner metadata cleanup result|**Finished with multiple TypeErrors**|Finished correctly|

Result of binary files diff:
![compare](https://user-images.githubusercontent.com/1886660/83965385-b35c3b80-a8b3-11ea-91fd-b9ef87dfde44.png)

There is one more simple thing that I have tried so far. I tried to open the sources of both files in VS Code. The result was interesting:
|Category \ File|Original file|Downloaded from GitHub|
|-|-|-|
|File name|test.jpg|83955052-43b46500-a84f-11ea-8c52-fb98adad5c74.jpg|
|File path|_D:\Sprzeda**ż**_|_D:\Tests_|
|VS Code response|Open with prompt: `The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?`|Open file correctly and previewed the image|

### Checking the differences
The last prompt message and the fact that contents of both files are identical directed me towards the only visible difference: **file paths**.

I moved original file to the path of copy and both ExifCleaner and VSCode started working.

### Conclusions
It looks like ExifCleaner has a problem with Unicode / UTF-8 signs in file paths (please pay attention to `ż` in path `D:\Sprzedaż`). In my example it was one of consonants used in polish language.

Hope it helps you :)

**Comment by szTheory** [comment] 2020-06-07 13:36
Thanks for your extensive legwork! I should have recognized the error earlier, it's the same as [another use encountered with a UTF-8 filename containing ñ or ç](https://github.com/szTheory/exifcleaner/issues/17) (see link). I was able to reproduce. It appears to be some kind of configuration issue with underlying `exiftool` command itself. I tried a couple of things (namely passing some command line arguments to exitfool like `-charset filename=UTF8`) but could not fix it immediately, and I've been too busy lately to spend more time chasing it.

I know it's a tall order to ask, but perhaps you could dig in a bit? I've ported the code base over to TypeScript (3.2 was JavaScript) so maybe it would help you tinker since there are compiler error messages now. Actually if you could reproduce with the bare `exiftool` command line tool on its own first, then that would definitely make fixing it even easier since we'd know exactly what command line arguments are needed to support UTF-8 filenames on Widnows. But perhaps it's an issue with how how the ExifCleaner code is interfacing with the command line tool.

It errors when getting exif on this line https://github.com/szTheory/exifcleaner/blob/d94414ce6e130abceb6f1edcd204fc781f78abf1/src/renderer/add_files.ts#L147 and will probably error when removing exif on this line as well https://github.com/szTheory/exifcleaner/blob/d94414ce6e130abceb6f1edcd204fc781f78abf1/src/renderer/add_files.ts#L127

**Comment by szTheory** [comment] 2020-06-09 16:57
Closing this as a duplicate of https://github.com/szTheory/exifcleaner/issues/17. But it will be linked from that URL, don't worry.

**Closed by szTheory** 2020-06-09 16:57 UTC
Labels: bug, windows

**Comment by m1chu** [comment] 2020-07-08 21:06
It's been a long time since my report, but finally I found some time to review the code. It looks like my problem with utf-8 encoded signs in path has been resolved.

Fix is between commit [244d96f2e91e0751e7f19b95df38d2dd981dd465](https://github.com/szTheory/exifcleaner/commit/244d96f2e91e0751e7f19b95df38d2dd981dd465) and the commit tagged as [3.2.0 release](https://github.com/szTheory/exifcleaner/commit/9a43859fcf1de4b90c9fda880ba54d3e83211514).

I switched to 244d96f2e91e0751e7f19b95df38d2dd981dd465, run an application and images from path `D:\Sprzedaż` have been properly cleaned.

**Comment by szTheory** [comment] 2020-07-08 21:10
That's good to hear, thanks for the report. I'm not sure how any changes I've made would have fixed the issue, so I'll have to test it myself to be sure. Have a good one.

**Comment by m1chu** [comment] 2020-07-09 08:18
Sadly, my previous comment was not entirely correct.

Bug has not been corrected, but the application's behavior has changed:
1. In `3.2.0 release` we got `TypeError` and column `# Exif Before` remained empty (like described in my post content).
2. Some `newer commit` (maybe 244d96f2e91e0751e7f19b95df38d2dd981dd465 ?) caused such a change that the `TypeError` does not occur anymore and the column `# Exif Before` is filled with the value zero.

The application still doesn't find any metadata to clear when path has some utf-8 special signs.

**Comment by szTheory** [comment] 2020-07-10 02:52
Thanks, I have a bit of free time so I'm circling back to look at this again. My WIP fix is at https://github.com/szTheory/exifcleaner/pull/62, going to test it on Windows soon.

**Comment by szTheory** [comment] 2020-07-11 01:37
@m1chu Sorry for the delay but I've finally fixed this in [v3.1.1](https://github.com/szTheory/exifcleaner/releases/tag/v3.3.1). Please let me know if you encounter further issues.

**Comment by m1chu** [comment] 2020-07-12 11:09
@szTheory, no need to apologize :) I did some tests. The result is positive. Thank you!

![fixed](https://user-images.githubusercontent.com/1886660/87244875-e8265a00-c440-11ea-9114-a5ef1e0e3475.png)

**Comment by szTheory** [comment] 2020-07-15 02:30
@m1chu Hi, I was wondering if you'd be interested in translating ExifCleaner to Polish. I've made it very easy, all you have to do is go to https://github.com/szTheory/exifcleaner/blob/master/.resources/strings.json and click on "Edit this file" and add an entry for Polish underneath the other ones with the language code `"pl"`. Full instructions are [here](https://github.com/szTheory/exifcleaner#adding-a-translation).
